### PR TITLE
First task

### PR DESCRIPTION
**Pull request by mhmdxx5**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — APPROVED** [review]
Approved! Go ahead and merge this PR. Quickly now.

**Comment by mhmdxx5** [comment]
merging firs task (with CODEOWNERS file)

**Comment by mhmdxx5** [comment]
merging 2 commits 
(first task)

**Pull request merged**
